import type {Messages} from "@/lib/i18n";
import Link from 'next/link';
export function SectionHeading({number,label,title,description}:{number:string;label:string;title:string;description?:string}){return <div className="section-heading"><div className="eyebrow"><span className="section-number">{number}</span>{label}</div><div><h2>{title}</h2>{description&&<p className="section-description">{description}</p>}</div></div>}
export function SignalPanel({t}:{t:Messages}){return <figure className="signal-panel"><div className="panel-heading"><span className="mono">SKYNET / ACOUSTIC NODE</span><span className="signal-dot" aria-hidden="true"/></div><div className="signal-graphic" aria-hidden="true"><div className="signal-ring ring-one"/><div className="signal-ring ring-two"/><div className="signal-ring ring-three"/><div className="crosshair horizontal"/><div className="crosshair vertical"/><div className="node-core"><span>01</span></div><span className="graphic-label">{t.diagramCaption}</span></div><div className="waveform" aria-hidden="true">{Array.from({length:48},(_,i)=><span key={i} style={{height:`${12+Math.round(Math.abs(Math.sin(i*.83)*Math.cos(i*.27))*46)}px`}}/>)}</div><figcaption><span>{t.diagramCaption}</span><small>{t.diagramNote}</small></figcaption></figure>}
export function StatusStrip({t}:{t:Messages}){return <div className="status-strip"><div><span className="signal-dot" aria-hidden="true"/><strong>{t.stageLabel}</strong><span>{t.stageDescription}</span></div><div><strong>01</strong><span>{t.nodeDescription}</span></div><div><strong>{t.nextLabel}</strong><span>{t.nextDescription}</span></div></div>}
export function Roadmap({t}:{t:Messages}){return <ol className="roadmap"><li className="current"><span className="step-number">01</span><div className="tag">{t.roadmap1Tag}</div><h3>{t.roadmap1Title}</h3><p>{t.roadmap1Body}</p></li><li><span className="step-number">02</span><div className="tag pending">{t.roadmap2Tag}</div><h3>{t.roadmap2Title}</h3><p>{t.roadmap2Body}</p></li><li><span className="step-number">03</span><div className="tag future">{t.roadmap3Tag}</div><h3>{t.roadmap3Title}</h3><p>{t.roadmap3Body}</p></li></ol>}
export function NextPage({label,title,href,action}:{label:string;title:string;href:string;action:string}){return <section className="next-page"><div className="wrap"><div><div className="eyebrow">{label}</div><h2>{title}</h2></div><Link className="btn primary" href={href}>{action}<span aria-hidden="true">↗</span></Link></div></section>}

export function HeroHeadline({text}:{text:string}){const lines=text.split("\n");return <h1>{lines.map((line,i)=><span className={i===lines.length-1?"accent headline-line":"headline-line"} key={i}>{line}</span>)}</h1>}
