import {ConceptIllustration} from '@/components/ConceptIllustration';
import {messages,localizedPath,type Locale} from "@/lib/i18n";
import {Shell} from '@/components/Shell';
import {HeroHeadline,SectionHeading,NextPage} from '@/components/Editorial';
export default function Investors({locale="uk"}:{locale?:Locale}){const t=messages(locale);return <Shell locale={locale} page="investors"><main id="content">
  <div className="wrap hero hero-mobile-art hero-secondary"><div className="hero-copy"><div className="hero-heading"><div className="eyebrow">{t.investorsEyebrow}</div><HeroHeadline text={t.investorsHeadline}/></div><div className="hero-details"><p className="lead">{t.investorsLead}</p><p className="hero-note">{t.productStatus} · {t.nextDescription}</p><div className="actions"><a className="btn primary" href="#evidence">{t.evidenceAction} <span aria-hidden="true">↓</span></a><a className="btn" href="#risks">{t.risksAction}</a></div></div></div><aside className="brief-panel investor-brief illustrated-brief"><ConceptIllustration kind="signal" t={t} priority/><div className="hero-brief-content"><div className="eyebrow">{t.currentScopeLabel}</div><dl><div><dt>{t.productLabel}</dt><dd>{t.productStatus}</dd></div><div><dt>{t.fieldLabel}</dt><dd>{t.fieldStatus}</dd></div><div><dt>{t.businessLabel}</dt><dd>{t.businessStatus}</dd></div><div><dt>{t.transactionsLabel}</dt><dd>{t.transactionsStatus}</dd></div></dl></div></aside></div>
  <section id="opportunity"><div className="wrap"><SectionHeading number="01" label={t.opportunityLabel} title={t.opportunityTitle} description={t.opportunityDescription}/><div className="grid"><article className="card"><span className="card-index">01</span><h3>{t.opportunity1Title}</h3><p>{t.opportunity1Body}</p></article><article className="card"><span className="card-index">02</span><h3>{t.opportunity2Title}</h3><p>{t.opportunity2Body}</p></article><article className="card"><span className="card-index">03</span><h3>{t.opportunity3Title}</h3><p>{t.opportunity3Body}</p></article></div></div></section>
  <section id="evidence"><div className="wrap"><SectionHeading number="02" label={t.evidenceLabel} title={t.evidenceTitle} description={t.evidenceDescription}/><div className="evidence-grid"><article className="card"><span className="card-index">{t.evidence1Label}</span><h3>{t.evidence1Title}</h3><p>{t.evidence1Body}</p><span className="tag pending">{t.evidence1Tag}</span></article><article className="card"><span className="card-index">{t.evidence2Label}</span><h3>{t.evidence2Title}</h3><p>{t.evidence2Body}</p><span className="tag future">{t.evidence2Tag}</span></article><article className="card"><span className="card-index">{t.evidence3Label}</span><h3>{t.evidence3Title}</h3><p>{t.evidence3Body}</p><span className="tag future">{t.evidence3Tag}</span></article><article className="card"><span className="card-index">{t.evidence4Label}</span><h3>{t.evidence4Title}</h3><p>{t.evidence4Body}</p><span className="tag pending">{t.evidence4Tag}</span></article></div></div></section>
  <section id="pilot"><div className="wrap"><SectionHeading number="03" label={t.pilotLabel} title={t.pilotTitle} description={t.pilotDescription}/><div className="principle-list"><div><span>01</span><h3>{t.pilot1Title}</h3><p>{t.pilot1Body}</p></div><div><span>02</span><h3>{t.pilot2Title}</h3><p>{t.pilot2Body}</p></div><div><span>03</span><h3>{t.pilot3Title}</h3><p>{t.pilot3Body}</p></div></div></div></section>
  <section id="risks"><div className="wrap"><SectionHeading number="04" label={t.risksLabel} title={t.risksTitle}/><div className="principle-list"><div><span>01</span><h3>{t.risk1Title}</h3><p>{t.risk1Body}</p></div><div><span>02</span><h3>{t.risk2Title}</h3><p>{t.risk2Body}</p></div><div><span>03</span><h3>{t.risk3Title}</h3><p>{t.risk3Body}</p></div></div></div></section>
  <section><div className="wrap investor-note"><div className="eyebrow">{t.limitsLabel}</div><h2>{t.limitsTitle}</h2><p className="section-description">{t.limitsBody}</p></div></section>
  <NextPage label={t.backLabel} title={t.backTitle} href={localizedPath(locale,"/")} action={t.homeAction}/>
</main></Shell>}
