import {messages,localizedPath,type Locale} from "@/lib/i18n";
import {Shell} from '@/components/Shell';
import {PaymentGate} from '@/components/PaymentGate';
import {ShareButton} from '@/components/ShareButton';
import {HeroHeadline,SectionHeading,Roadmap,NextPage} from '@/components/Editorial';
export default function Crowdfunding({locale="uk"}:{locale?:Locale}){const t=messages(locale);return <Shell locale={locale} page="support"><main id="content">
  <div className="wrap hero hero-secondary"><div className="hero-copy"><div className="eyebrow">{t.supportEyebrow}</div><HeroHeadline text={t.supportHeadline}/><p className="lead">{t.supportLead}</p><div className="actions"><a className="btn primary" href="#participate">{t.participateAction} <span aria-hidden="true">↓</span></a><a className="btn" href="#funding">{t.fundingAction}</a></div></div><aside className="brief-panel"><div className="eyebrow">{t.focusLabel}</div><div className="big-number">01<span>{t.nodeUnit}</span></div><h2>{t.benchTitle}</h2><p>{t.benchBody}</p><div className="panel-divider"/><span className="tag pending">{t.roadmap2Tag}</span></aside></div>
  <section><div className="wrap"><SectionHeading number="01" label={t.roadmapLabel} title={t.supportRoadmapTitle}/><Roadmap t={t}/></div></section>
  <section id="participate"><div className="wrap"><SectionHeading number="02" label={t.participateLabel} title={t.participateTitle} description={t.participateDescription}/><div className="support-grid"><article className="card support-card"><span className="card-index">{t.shareLabel}</span><h3>{t.shareTitle}</h3><p>{t.shareBody}</p><ShareButton href={localizedPath(locale)} label={t.shareAction} success={t.shareSuccess} fallback={t.shareFallback}/></article><article className="card support-card"><span className="card-index">{t.understandLabel}</span><h3>{t.understandTitle}</h3><p>{t.understandBody}</p><a className="text-link" href="#questions">{t.questionsAction} <span aria-hidden="true">↗</span></a></article></div></div></section>
  <section id="funding"><div className="wrap funding-layout"><div><div className="eyebrow">{t.fundingAction}</div><h2>{t.fundingTitle}</h2><p className="section-description">{t.fundingDescription}</p></div><div className="funding-status"><span className="tag pending">{t.fundingClosed}</span><PaymentGate notice={t.paymentNotice}/></div></div></section>
  <section id="questions"><div className="wrap"><SectionHeading number="03" label={t.questionsLabel} title={t.questionsTitle}/><div className="faq"><details open><summary>{t.faq1Question}</summary><p>{t.faq1Answer}</p></details><details><summary>{t.faq2Question}</summary><p>{t.faq2Answer}</p></details><details><summary>{t.faq3Question}</summary><p>{t.faq3Answer}</p></details><details><summary>{t.faq4Question}</summary><p>{t.faq4Answer}</p></details></div></div></section>
  <NextPage label={t.deeperLabel} title={t.deeperTitle} href={localizedPath(locale,"/investors")} action={t.investorsAction}/>
</main></Shell>}
